# SPDX-FileCopyrightText: 2026 ash_evidence contributors <https://github.com/lukegalea/ash_evidence>
#
# SPDX-License-Identifier: MIT

# Dialyzer is advisory in this repository (see mix.exs: findings nobody
# has canonical guidance for; the 1.18+ type checker in
# `mix compile --warnings-as-errors` is the real static-analysis gate).
# This file records the known findings so the advisory job reads clean.
#
[
  # AshEvidence.PostgrexTypes is GENERATED by Postgrex.Types.define/3
  # (lib/ash_evidence/postgrex_types.ex); the finding below is raised
  # inside postgrex's own codegen template that materialises the module —
  # not in this package's logic.
  {"deps/postgrex/lib/postgrex/type_module.ex", :improper_list_constr}
]
