# SPDX-FileCopyrightText: 2026 ash_evidence contributors <https://github.com/lukegalea/ash_evidence>
#
# SPDX-License-Identifier: MIT

defmodule AshEvidence.Assertions.Fragment do
  @moduledoc """
  The evidence-assertion fragment: the attributes, the action and the
  pure derived change a host includes in its own resource.

  The package never defines the persisted assertion — the host includes
  this fragment on its platform base so the host's AshEvents audit,
  tenancy and ownership apply (the `Ledger.Fragment` pattern; see
  `AshEvidence.Assertions` for the contract and the erasure posture).

  ## Replay safety is structural (RFC §6.1)

  The `:record` create **accepts every field as input** — disposition,
  distribution, rule version, observation ids, the admission handoff
  keys. Its only change computes one pure derived field (`record_hash`,
  the §4.5 digest over the inputs), identical on replay. There is no
  I/O, no clock read for an identity field, and no instrument call
  anywhere on the create path: during AshEvents replay the same inputs
  rebuild the same row and no model is consulted. `created_at` is the
  one database-generated field (declare it as the resource's
  `create_timestamp` in the events config; AshEvents restores it on
  replay).

  The aggregation runs BEFORE the create, in the host's orchestrator
  (`AshEvidence.Assertions.Aggregation.aggregate/1`) — the assertion
  records what the rule produced, it does not re-run it.

  ## Fields

  All envelope-class: ids (packet/evaluation/observation references —
  opaque, deliberately NOT foreign keys, so the assertion survives the
  blob-class records' erasure and reads afterwards as references to
  things that no longer resolve), digests, the frozen disposition, the
  distribution as DECIMAL STRINGS (the DMN bridge reads decimals), and
  the admission handoff keys (`subject`, `predicate`,
  `subject_state_digest`, `question_set_hash`).
  """

  @moduledoc since: "0.1.0"

  use Spark.Dsl.Fragment, of: Ash.Resource

  alias AshEvidence.Assertions

  attributes do
    # The assertion id is generated by the orchestrator and passed in —
    # the caller's idempotency key (the observation-fragment rule).
    attribute :id, :uuid,
      primary_key?: true,
      allow_nil?: false,
      default: &Ash.UUID.generate/0,
      writable?: true,
      public?: true

    # The one database-generated field; AshEvents restores it on replay
    # (declare as the events config's create_timestamp).
    create_timestamp :created_at

    attribute :record_version, :string,
      writable?: false,
      default: &Assertions.record_version/0,
      public?: true,
      description: "The record schema version, major only (§11)."

    attribute :record_hash, :string,
      writable?: true,
      public?: true,
      description:
        "Digest of the record's own canonical JSON minus record_hash minus created_at (§4.5); computed by the :record change from inputs."

    # Opaque cross-package references — deliberately NOT foreign keys:
    # the packet and evaluation are blob-class and cascade away with
    # their document version; the assertion is envelope-class and
    # survives, reading afterwards as a reference to something that no
    # longer resolves (the sanctioned posture).
    attribute :packet_id, :uuid, public?: true
    attribute :evaluation_id, :uuid, public?: true

    attribute :disposition, :atom,
      allow_nil?: false,
      public?: true,
      constraints: [
        one_of: [:supports, :contradicts, :insufficient, :not_applicable, :wrong_scope]
      ],
      description: "The aggregate value, the frozen evidence vocabulary — never an admission."

    attribute :distribution, :map,
      allow_nil?: false,
      public?: true,
      description:
        "Disposition -> decimal string (§4.3). The DMN bridge reads decimal strings; probabilities never travel as floats."

    attribute :aggregation_rule_version, :string,
      allow_nil?: false,
      public?: true,
      description:
        "The versioned composition rule that produced this assertion (§2.6) — recalibrating the rule is a new version and re-earns everything downstream."

    attribute :observation_ids, {:array, :uuid},
      allow_nil?: false,
      public?: true,
      default: [],
      description:
        "The judgment-ledger rows this aggregate composes — pointers only; answers are never copied."

    # The admission handoff keys (§7.4): what the banding and admission
    # chain needs to find the eventual fact this evidence is about.
    attribute :subject, :map,
      allow_nil?: false,
      public?: true,
      constraints: [
        fields: [
          type: [type: :string, allow_nil?: false],
          id: [type: :string, allow_nil?: false]
        ]
      ]

    attribute :predicate, :string, allow_nil?: false, public?: true

    attribute :subject_state_digest, :string,
      allow_nil?: false,
      public?: true,
      description: "The §7.4 freshness binding — the state the predicate was evaluated against."

    attribute :question_set_hash, :string, allow_nil?: false, public?: true
  end

  actions do
    create :record do
      description """
      Records an assertion. Accepts every field as input, including the
      aggregate outcome — the aggregation ran in the orchestrator before
      this action, and replay rebuilds the row from these inputs without
      ever consulting a model (§6.1).
      """

      accept [
        :id,
        :packet_id,
        :evaluation_id,
        :disposition,
        :distribution,
        :aggregation_rule_version,
        :observation_ids,
        :subject,
        :predicate,
        :subject_state_digest,
        :question_set_hash
      ]

      # Pure derived fields from inputs only (§6.1): identical on
      # replay, no I/O, no clock.
      change {AshEvidence.Assertions.Changes.DeriveRecord, []}
    end

    defaults [:read]
  end

  identities do
    # The assertion id is the orchestrator's idempotency key.
    identity :unique_id, [:id]
  end
end

defmodule AshEvidence.Assertions.Changes.DeriveRecord do
  @moduledoc false
  # The :record create's derived field — a PURE function of the inputs:
  # identical on replay, no I/O, no clock. `record_version` is a
  # constant default (also pure); `created_at` is database-generated
  # and excluded from the hash, exactly like the observation fragment's
  # `recorded_at`.
  use Ash.Resource.Change

  alias AshEvidence.Assertions

  @impl true
  def change(changeset, _opts, _context) do
    record_hash =
      Ash.Changeset.before_action(changeset, fn changeset ->
        hash =
          Assertions.record_hash(%{
            id: Ash.Changeset.get_attribute(changeset, :id),
            record_version: Assertions.record_version(),
            packet_id: Ash.Changeset.get_attribute(changeset, :packet_id),
            evaluation_id: Ash.Changeset.get_attribute(changeset, :evaluation_id),
            disposition: Ash.Changeset.get_attribute(changeset, :disposition),
            distribution: Ash.Changeset.get_attribute(changeset, :distribution),
            aggregation_rule_version:
              Ash.Changeset.get_attribute(changeset, :aggregation_rule_version),
            observation_ids: Ash.Changeset.get_attribute(changeset, :observation_ids),
            subject: Ash.Changeset.get_attribute(changeset, :subject),
            predicate: Ash.Changeset.get_attribute(changeset, :predicate),
            subject_state_digest: Ash.Changeset.get_attribute(changeset, :subject_state_digest),
            question_set_hash: Ash.Changeset.get_attribute(changeset, :question_set_hash)
          })

        Ash.Changeset.force_change_attribute(changeset, :record_hash, hash)
      end)

    record_hash
  end
end
