# SPDX-FileCopyrightText: 2026 ash_evidence contributors <https://github.com/lukegalea/ash_evidence>
# SPDX-License-Identifier: MIT

defmodule AshEvidence.Repo.Migrations.InitialResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:addressed_atoms, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:seq, :bigint, null: false)
      add(:text, :text, null: false)
      add(:source_ids, {:array, :uuid}, default: [])
      add(:bbox, :map)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:document_version_id, :uuid, null: false)
    end

    create unique_index(:addressed_atoms, [:document_version_id, :seq],
             name: "addressed_atoms_unique_seq_per_version_index"
           )

    alter table(:addressed_atoms) do
      add(:parse_run_id, :uuid, null: false)
    end

    create table(:document_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:addressed_atoms) do
      modify(
        :document_version_id,
        references(:document_versions,
          column: :id,
          name: "addressed_atoms_document_version_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:document_versions) do
      add(:kind, :text, null: false)
      add(:bytes, :binary, null: false)
      add(:sha256, :text, null: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:document_versions, [:sha256],
             name: "document_versions_unique_content_index"
           )

    create table(:parse_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:addressed_atoms) do
      modify(
        :parse_run_id,
        references(:parse_runs,
          column: :id,
          name: "addressed_atoms_parse_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:parse_runs) do
      add(:instrument, :text, null: false)
      add(:config, :map, default: %{})
      add(:status, :text, null: false, default: "pending")

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :document_version_id,
        references(:document_versions,
          column: :id,
          name: "parse_runs_document_version_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:parse_runs, "parse_runs_document_version_id_fkey"))

    alter table(:parse_runs) do
      remove(:document_version_id)
      remove(:created_at)
      remove(:status)
      remove(:config)
      remove(:instrument)
    end

    drop(constraint(:addressed_atoms, "addressed_atoms_parse_run_id_fkey"))

    drop(constraint(:addressed_atoms, "addressed_atoms_document_version_id_fkey"))

    alter table(:addressed_atoms) do
      modify(:parse_run_id, :uuid)
    end

    drop(table(:parse_runs))

    drop_if_exists(
      unique_index(:document_versions, [:sha256], name: "document_versions_unique_content_index")
    )

    alter table(:document_versions) do
      remove(:created_at)
      remove(:sha256)
      remove(:bytes)
      remove(:kind)
    end

    alter table(:addressed_atoms) do
      modify(:document_version_id, :uuid)
    end

    drop(table(:document_versions))

    alter table(:addressed_atoms) do
      remove(:parse_run_id)
    end

    drop_if_exists(
      unique_index(:addressed_atoms, [:document_version_id, :seq],
        name: "addressed_atoms_unique_seq_per_version_index"
      )
    )

    drop(table(:addressed_atoms))
  end
end
