# SPDX-FileCopyrightText: 2026 ash_evidence contributors <https://github.com/lukegalea/ash_evidence>
# SPDX-License-Identifier: MIT

defmodule AshEvidence.Repo.Migrations.AddPackets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:evidence_evaluations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:subject, :map, null: false)
      add(:predicate, :text, null: false)
      add(:rule_ref, :map)
      add(:question_set_hash, :text, null: false)
      add(:candidate_set_ids, {:array, :uuid}, null: false, default: [])
      add(:expansion_steps, {:array, :map}, null: false, default: [])
      add(:profile, :text, null: false)
      add(:call_shape, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:closed_at, :utc_datetime_usec)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :document_version_id,
        references(:document_versions,
          column: :id,
          name: "evidence_evaluations_document_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    create table(:evidence_packets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:candidate_atom_ids, {:array, :text}, null: false, default: [])
      add(:candidate_observations, :map, null: false, default: %{})
      add(:selected_atom_ids, {:array, :text}, null: false, default: [])
      add(:limiting_atom_ids, {:array, :text}, null: false, default: [])
      add(:missing_dimensions, {:array, :text}, null: false, default: [])
      add(:requires_expansion, :boolean, null: false, default: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :evaluation_id,
        references(:evidence_evaluations,
          column: :id,
          name: "evidence_packets_evaluation_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end
  end

  def down do
    drop(constraint(:evidence_packets, "evidence_packets_evaluation_id_fkey"))

    drop(table(:evidence_packets))

    drop(constraint(:evidence_evaluations, "evidence_evaluations_document_version_id_fkey"))

    drop(table(:evidence_evaluations))
  end
end
