# SPDX-FileCopyrightText: 2026 ash_evidence contributors <https://github.com/lukegalea/ash_evidence>
# SPDX-License-Identifier: MIT

defmodule AshEvidence.Repo.Migrations.AddRetrieval do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:addressed_atoms, ["(to_tsvector('english', text))"],
             name: "addressed_atoms_text_fts_index",
             using: "gin"
           )

    create table(:atom_representations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:representation, :text, null: false)
      add(:embedding, :vector)
      add(:embedding_model, :text)
      add(:embedding_model_version, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :addressed_atom_id,
        references(:addressed_atoms,
          column: :id,
          name: "atom_representations_addressed_atom_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:atom_representations, [:addressed_atom_id],
             name: "atom_representations_unique_atom_index"
           )

    alter table(:atom_representations) do
      add(
        :document_version_id,
        references(:document_versions,
          column: :id,
          name: "atom_representations_document_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    create index(:atom_representations, [:document_version_id])

    create table(:candidate_sets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:claim_hash, :text, null: false)
      add(:query_hashes, :map, default: %{})
      add(:k, :bigint, null: false)
      add(:lexical_config, :text, null: false, default: "english")
      add(:embedding_model, :text)
      add(:embedding_model_version, :text)
      add(:hypotheses, {:array, :text}, null: false, default: [])
      add(:candidates, {:array, :map}, null: false, default: [])

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :document_version_id,
        references(:document_versions,
          column: :id,
          name: "candidate_sets_document_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end
  end

  def down do
    drop(constraint(:candidate_sets, "candidate_sets_document_version_id_fkey"))

    drop(table(:candidate_sets))

    drop_if_exists(index(:atom_representations, [:document_version_id]))

    drop(constraint(:atom_representations, "atom_representations_document_version_id_fkey"))

    drop(constraint(:atom_representations, "atom_representations_addressed_atom_id_fkey"))

    alter table(:atom_representations) do
      remove(:document_version_id)
    end

    drop_if_exists(
      unique_index(:atom_representations, [:addressed_atom_id],
        name: "atom_representations_unique_atom_index"
      )
    )

    drop(table(:atom_representations))

    drop_if_exists(
      index(:addressed_atoms, ["(to_tsvector('english', text))"],
        name: "addressed_atoms_text_fts_index"
      )
    )
  end
end
